### ISSUE TITLE
[BUG] Missing #include <variant> in include/rtcx/embed.hpp breaks build with GCC 16

### ISSUE THREAD

**Issue by karthikeyann** [rapidsai/librtcx#19]
## Describe the bug

`include/rtcx/embed.hpp` uses `std::variant` and `std::get_if` but does not include `<variant>`. It currently compiles because `<variant>` is pulled in transitively by another libstdc++ header; GCC 16's libstdc++ no longer provides it transitively, so the header fails to parse.

This is the usual missing-include breakage that surfaces on each GCC major bump.

The declarations that need it are at `embed.hpp:143-145`:

```cpp
using strings_t = std::vector<std::string_view>;
using ints_t    = std::vector<std::int64_t>;
using values_t  = std::variant<strings_t, ints_t>;   // line 145

std::map<std::string_view, values_t> arrays;
```

Resulting errors:

```
include/rtcx/embed.hpp:143:26: error: 'variant' in namespace 'std' does not name a template type
include/rtcx/embed.hpp:145:30: error: 'values_t' was not declared in this scope; did you mean 'value_type'?
include/rtcx/embed.hpp:151:32: error: request for member 'find' in 'arrays', which is of non-class type 'int'
include/rtcx/embed.hpp:184:27: error: 'get_if' is not a member of 'std'
```

## Steps/Code to reproduce bug

Build with GCC 16. In our case rtcx is pulled in as a libcudf dependency, and these targets failed:

```
cudf_fragments__jit_embed_run.dir/cudf_fragments__embed.cpp.o
cudf_cuda_embed__jit_embed_run.dir/cudf_cuda_embed__embed.cpp.o
```

## Expected behavior

The header includes the standard headers it uses, so it compiles independently of what other libstdc++ headers happen to pull in.

## Suggested fix

Add the include alongside the existing standard includes in `embed.hpp`:

```diff
 #include <utility>
 #include <vector>
+#include <variant>
```

I verified this locally: adding `#include <variant>` clears all of the errors above.

## Environment details

- Compiler: GCC 16.2.1 20260807 (Red Hat 16.2.1-1, `gcc-toolset-16`)
- CUDA: 13.4 (nvcc V13.4.92)
- OS: CentOS Stream 9
- Standard: `-std=gnu++20`
- Consumer: libcudf (commit `456580fcdd726380dcb3de6b9686e7d47d6dd0a2`, release/26.10), built from source by Velox with `VELOX_ENABLE_CUDF=ON`

## Additional context

Found while evaluating GCC 16 support for Velox's cuDF backend. The identical missing-`<variant>` problem also exists in cuDF itself and is filed as NVIDIA/cudf#24232.
